### ISSUE TITLE
Puppet compile test fails

### ISSUE THREAD

**Issue by BigAl** [electrical/puppet-lib-file_concat#14]
The current master fails the puppet catalog compile.

Notice: Compiled catalog for xxx in environment production in 29.92 seconds
Error: wrong number of arguments (1 for 0)
Wrapped exception:
wrong number of arguments (1 for 0)

It appears to work fine for the acceptance_test branch. Not being a Ruby person I don't have the solution yet to do a PR.

**Comment by electrical** [comment]
Hi,

Thank you very much for reporting it.
I'll have a look at this and see if i can find the issue.

**Comment by electrical** [comment]
Hi,

I just ran the acceptance tests on the master branch and ran without any issues.
How did you run the puppet code? Perhaps I overlooked something that i'm not testing on.

thanks!

**Comment by electrical** [comment]
Hi,

I'm very sorry for the bug. it was caused by a bit to much refactoring.
I've released 0.2.1 with the fix.

**Comment by BigAl** [comment]
No problem Richard I meant to get back to you yesterday with some more
debug output instead I spent the day chasing a issue create by the heira
2.0.0 ruby gem release. Anyway glad you found the issue.

cheers

alan
