### ISSUE TITLE
Latest changes cause autoload issue in tests

### ISSUE THREAD

**Issue by madAndroid** [electrical/puppet-lib-file_concat#21]
For some reason, not worked it out quite yet, the latest release appears to cause test failures:
```
     Failure/Error: it { should compile.with_all_deps }
       error during compilation: Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/posix: cannot load such file -- puppet/provider/file_concat on node andrews-mbp.int.stangl.co.za
```
When I pin the version to `0.2.1` in the `.fixtures.yaml`:
```
file_concat:
  repo: ispavailability/file_concat
  ref: '0.2.1'
```
the problem then goes away .. not sure which commit this is being caused by though

**Comment by electrical** [comment]
weird stuff. Haven't had any test failures like that in my acceptance tests. http://build-eu-00.elastic.co/view/Puppet/job/Puppet_File_Concat_Acceptance_Commit/

**Comment by madAndroid** [comment]
Yeah, it's very odd :-/ .. I'll see if I can track down what's going on

**Comment by electrical** [comment]
Which puppet version are you running on btw?

**Comment by madAndroid** [comment]
This is testing on `3.6.2` and `3.7.5` - happens with both, afaict

**Comment by electrical** [comment]
In the latest version we did split off some stuff to support windows and linux. but all linux testing is passing.
Anything else specific you are running like Puppet Server or something?

**Comment by madAndroid** [comment]
Nope, just a bunch of dependencies, nothing like Puppet Server

**Comment by madAndroid** [comment]
Stranger yet, is that a subsequent test of the same code path passes okay - so it's something to do with the way the autoloading is happening, afaict

**Comment by electrical** [comment]
Very weird. Just ran the acceptance testing again to make sure i wasn't talking crap and 3.2.x and 3.7.x ( both latest versions of those releases ) are all green.
http://build-eu-00.elastic.co/view/Puppet/job/Puppet_File_Concat_Acceptance_Commit/11/

Which version of puppet-rspec are you using?

**Comment by electrical** [comment]
I've pinged you on IRC as well, I think you are hitting this issue: https://github.com/rodjek/rspec-puppet/pull/237

**Comment by madAndroid** [comment]
Yup, that appears to be it :-/

When I add the (very hacky) workaround mentioned in [PUP-3336](https://tickets.puppetlabs.com/browse/PUP-3336):
```
diff --git a/puppet/spec/spec_helper.rb b/puppet/spec/spec_helper.rb
index 9a689d3..ddf668d 100644
--- a/puppet/spec/spec_helper.rb
+++ b/puppet/spec/spec_helper.rb
@@ -14,6 +14,8 @@ def project_root
   proj_root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
 end

+$: << "spec/fixtures/modules/file_concat/lib"
+
```
Tests then pass okay .. I'll close this issue then.. thanks for your help :)

**Comment by electrical** [comment]
Very sad bug :-(
Hope this can be solved very soon.

**Comment by madAndroid** [comment]
Yeah, let's hope so :-/
