### ISSUE TITLE
Could not autoload puppet/provider/file_concat/windows: no such file to load

### ISSUE THREAD

**Issue by szemlyanoy** [electrical/puppet-lib-file_concat#29]
Hi,

I faced with such error after installing logstash module and including it into node

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/windows: no such file to load

Module file_concat  being included into node profile also. 
What is the issue with that? 

Thanks in advance
Sergey

**Comment by electrical** [comment]
Hi,

My best guess you have an older version which has this bug.
Can you checkout the version here https://forge.puppetlabs.com/electrical/file_concat ?

**Comment by szemlyanoy** [comment]
Hi,

I've updated module version but the problem remained

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/windows: no such file to load -- puppet/provider/file_concat at /etc/puppet/../modules/logstash/manifests/config.pp:55:5 on node

Not sure what am I doing wrong?

Regards
Sergey

**Comment by szemlyanoy** [comment]
Sorry seems I messed up on my environment. Now looks ok

Thanks
Sergey

**Comment by electrical** [comment]
Np, glad you found it, was getting worried :-)
