### ISSUE TITLE
 Could not autoload puppet/type/file_concat: uninitialized constant Puppet::Type::File::Owner

### ISSUE THREAD

**Issue by KlavsKlavsen** [electrical/puppet-lib-file_concat#35]
Trying to upgrade to puppet 4.. using puppetserver 2.1.2 and puppet-agent-1.3.2-1.el7.x86_64

Using latest file_concat module (just cloned master and tried again) I get this error:
Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/file_concat: uninitialized constant Puppet::Type::File::Owner

This seems to have been an issue before:
https://tickets.puppetlabs.com/browse/SERVER-40

anyone using this module with puppet 4?

**Comment by electrical** [comment]
I think we solved this on IRC right? problem was a lingering version of the module.

**Comment by KlavsKlavsen** [comment]
yup.
