### ISSUE TITLE
Do better error reporting when we are not able to find the content

### ISSUE THREAD

**Issue by electrical** [electrical/puppet-lib-file_concat#6]
When we get an error that we can't get the content of a source file we need to assume that the source given is wrong.

**Comment by hunner** [comment]
The offending line: https://github.com/electrical/puppet-lib-file_concat/blob/0.1.0/lib/puppet/type/file_concat.rb#L118 (doesn't check if `tmp.nil?`)

**Comment by electrical** [comment]
Fix this issue by checking if tmp is nil and if so, ignore it.
See https://github.com/electrical/puppet-lib-file_concat/pull/10 for more details.
